### ISSUE TITLE
[❓] How do we add another language?

### ISSUE THREAD

**Issue by RCheesley** [mautic/townhall#18]
I have been asked if we can add Spanish as a language - could you tell me how we can do that? I could not find it in the Decidim docs.

**Comment by froger** [comment]
So instructions: 

- Edit the `DECIDIM_AVAILABLE_LOCALES` environment variables. (or edit the secrets.yml file /home/decidim/app/config/secrets.yml
- Access to the container, and run a console `bundle exec rails c`
- Update the available language for the Mautic Organization: `Decidim::Organization.first.update(available_locales: ["ca", "es", "en", "pt-BR", "jp"])`
- Follow the [Fixing Locales Documentation](https://docs.decidim.org)
- Restart the instance.

**Comment by RCheesley** [comment]
Awesome thank you so much for giving us the instructions!  I hope that we can put together a wiki so that we can explain to people how they can get access to the infrastructure and/or make PRs  going forward!
